export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';
export const CONVERT_CELSIUS_TO_FAHRENHEIT = "CONVERT_CELSIUS_TO_FAHRENHEIT";
export const CONVERT_FAHRENHEIT_TO_CELSIUS = "CONVERT_FAHRENHEIT_TO_CELSIUS";
export const SAVE_CITY = "SAVE_CITY";
export const SAVE_FORCAST = "SAVE_FORCAST";
